### ISSUE TITLE
Postgrex is erroring on throttle/buggy rate limiter

### ISSUE THREAD

**Issue by Chlorophytus** [Chlorophytus/ExSemantica#2]
This may have to do with `Process.sleep` issues.
```
[info] Postgrex.Protocol (#PID<0.570.0>) disconnected: ** (DBConnection.ConnectionError) client #PID<0.908.0> exited
```
I might be one to solve this, I need to do so in a few days, unless someone can solve it...

**Comment by miorapkmn** [comment]
Hi

**Comment by Chlorophytus** [comment]
I may just remove the delays. [They apparently cause a problem with Cowboy.](https://elixirforum.com/t/soft-rate-limiting-incoming-api-requests-connections-approach-by-slowing-them-down/35705/6)

> Hi

Hello.

**Comment by Chlorophytus** [comment]
With regards to this I have added proper debouncing to the rate limiters a long time ago.
